# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{statsd-ruby}
  s.version = "0.3.0"
  s.authors = ["Rein Henrichs"]
  s.date = %q{2011-06-24}
  s.description = %q{A Statsd client in Ruby}
  s.email = %q{rein@phpfog.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/statsd.rb",
    "spec/helper.rb",
    "spec/statsd_spec.rb",
    "statsd-ruby.gemspec"
  ]
  s.homepage = %q{http://github.com/reinh/statsd}
  s.licenses = ["MIT"]
  s.summary = "statsd for ruby"
  #s.require_paths = ["lib"]
end

